version: "3.9"
services:
  pg:
    image: postgres:13.3
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - pg_example_vol:/var/lib/postgresql/data # Assign pg_example_vol to postgres database
volumes:
  # docker volume create pg_example_vol
  pg_example_vol:
    external: true
